name: 'Dev Server Deployment'

on:
  push:
    branches:
      - stagingv2

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ vars.ORG_NAME }}
  APP_NAME: horizon-frontend-two

jobs:
  deployOptisageFrontend:
    name: Optisage Frontend Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build, tag, and push image to GHCR
      id: build-image
      env:
        IMAGE_NAME: ${{ env.APP_NAME }}
        COMMIT_ID: ${{ github.sha }}
        ENV: ${{ secrets.STAGING_ENV }}
      run: |
        echo "$ENV" >> .env
        IMAGE_TAG=$(echo $COMMIT_ID | cut -c 1-7)
        docker build -t $REGISTRY/$REPO_NAME/$IMAGE_NAME:develop-$IMAGE_TAG .
        docker push $REGISTRY/$REPO_NAME/$IMAGE_NAME:develop-$IMAGE_TAG
        echo "image=$REGISTRY/$REPO_NAME/$IMAGE_NAME:develop-$IMAGE_TAG" >> $GITHUB_OUTPUT
        
    - name: Deploy to Server Instance
      env:
          IMAGE: ${{ steps.build-image.outputs.image }}
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
          APP: ${{ env.APP_NAME }}
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: IMAGE,TOKEN,APP
          script: |
            echo "$TOKEN" | docker login ghcr.io -u USERNAME --password-stdin
            export DOCKER_IMAGE="$IMAGE"
            envsubst < /home/ubuntu/docker/dev-"$APP".yaml > /home/ubuntu/qace/dev-"$APP"/compose.yaml
            docker rm -f dev-"$APP"
            docker system prune -af
            docker compose -f /home/ubuntu/qace/dev-"$APP"/compose.yaml up -d
            docker ps
